title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          startdate:
            label: Start Date
            type: date
          enddate:
            label: End Date
            type: date
          artists:
            type: text
          additionalinfo:
            label: Additional Information (optional)
            type: text
          photocredits:
            label: Photography Credits (optional)
            type: text
  - width: 1/2
    sections:
      pdfs:
        label: PDF
        query: page.documents
        type: files
        layout: list
      images:
        query: page.images
        type: files
        layout: cards
        image:
          ratio: 1/1
