title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          date:
            label: Date
            type: text
          artists:
            type: text
          additionalinfo:
            label: Additional Information (optional)
            type: text
          photocredits:
            label: Photography Credits (optional)
            type: text
  - width: 1/2
    sections:
      previewimg:
        label: Preview Image for Homepage (optional)
        type: files
        template: previewimg
        layout: list
        sortable: false
        max: 1
      projecttexts:
        label: Project Texts (PDF)
        icon: document
        info: "{{ file.linktext }}"
        back: white
        template: projecttexts
        type: files
        layout: list
        sortable: true
        empty: No documents yet
      projectimages:
        label: Project Images (JPG, PNG, GIF)
        info: "{{ file.caption }}"
        template: projectimages
        type: files
        layout: cards
        empty: No images yet
        sortable: true
        image:
          ratio: 1/1
